version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
      - ./paraphrase-multilingual-MiniLM-L12-v2:/app/paraphrase-multilingual-MiniLM-L12-v2 
      - /home/ekaterina/Desktop/classifier-llm/containers.tsv:/app/containers.tsv
      - ./HSCodeandDescription.xlsx:/app/HSCodeandDescription.xlsx
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./paraphrase-multilingual-MiniLM-L12-v2:/app/paraphrase-multilingual-MiniLM-L12-v2 
      - /home/ekaterina/Desktop/classifier-llm/containers.tsv:/app/containers.tsv
      - ./HSCodeandDescription.xlsx:/app/HSCodeandDescription.xlsx
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  qdrant_data:
